# Generated by Django 2.1.5 on 2019-02-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=20)),
                ('leader', models.BooleanField(default=False)),
                ('operator', models.BooleanField(default=False)),
                ('document', models.ImageField(blank=True, upload_to='%Y/%m/%d/orig')),
                ('discription', models.TextField()),
                ('likelions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelion.likelion')),
            ],
        ),
    ]
