# Generated by Django 2.1.5 on 2019-02-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('description', models.TextField(default='설명을 입력해 주세요.')),
                ('git_link', models.CharField(blank=True, max_length=125, null=True)),
                ('blog_link', models.CharField(blank=True, max_length=125, null=True)),
                ('likelion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelion.likelion')),
            ],
        ),
    ]
